# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Exhibitor.create([
	# { name: '', img: '', site: '' }
	{ name: 'Warped Imagination', img: 'WarpedImagination.png', site: 'http://warpedimagination.com', is_featured: true },
	{ name: 'VR Live', img: 'VRLive.png', site: 'http://www.vrlive.com/', is_featured: true },
	{ name: 'Vrideo', img: 'VRideo.png', site: 'http://www.vrideo.com', is_featured: true },
	{ name: 'Oval Integration', img: 'Oval.png', site: 'http://www.ovalintegration.com/', is_featured: true },
	{ name: 'Otherworld Interactive', img: 'Otherworld.png', site: 'http://www.otherworldinteractive.com', is_featured: true },
	{ name: 'Sidekick VR', img: 'Sidekick.png', site: 'http://www.sidekickvrgames.com', is_featured: true },
	{ name: 'Funktronic Labs', img: 'Funktronic.png', site: 'http://funktroniclabs.com/collider', is_featured: true },
	{ name: 'Microsoft', img: 'Microsoft.png', site: 'https://www.microsoft.com/en-us/default.aspx', is_featured: true },
	{ name: 'Otoy', img: 'Otoy.png', site: 'http://www.otoy.com', is_featured: true },
	{ name: 'Temple Gate Games', img: 'Bazaar.png', site: 'http://www.templegatesgames.com/', is_featured: true },
	{ name: '360 Heros', img: '360Heros.png', site: 'http://www.360heros.com/', is_featured: true },
	{ name: 'Flarb', img: 'Flarb.png', site: 'http://www.flarb.com', is_featured: true },
	{ name: 'RocketSail', img: 'RocketSail.png', site: 'http://www.rocketsail.com' },
	{ name: 'Dash VR', img: 'DashVR.png', site: 'http://getdashvr.com' },
	{ name: 'Labcoat Studios', img: 'Labcoat.png', site: 'http://vrjam.challangepost.com/submissions/36460-re-entry' },
	{ name: 'Zenka', img: 'Zenka.png', site: 'http://www.zenka.org' },
	{ name: 'Monster VR', img: 'MonsterVR.png', site: 'http://www.monstervr.com/', custom_class: 'half' },
	{ name: 'V', img: 'V.png', site: 'http://startwithv.com', custom_class: 'half' },
	{ name: 'Next VR', img: 'NextVR.png', site: 'http://nextvr.com' },
	{ name: 'Freeform Labs', img: 'ElemenTerra.png', site: 'http://elementerravr.com' },
	{ name: 'Studio Transcendent', img: 'StudioTranscendent.png', site: 'http://studiotranscendent.com' },
	{ name: 'Dandelion VR', img: 'Dandelion.jpg', site: 'http://vrjam.challengepost.com/submissions/36441-dandelion' },
	{ name: 'Immersive Entertainment', img: 'IEI.png', site: 'http://www.immersiveent.com' },
	{ name: 'New Deal Studios', img: 'NewDealStudios.png', site: 'http://www.newdealstudio.com/virtual-reality', custom_class: 'half' },
	{ name: 'The Department of Silly Stuff', img: 'FacetedFlight.png', site: 'http://www.facetedflight.com', custom_class: 'half' },
	{ name: 'Really Big Pictures', img: 'RBP.png', site: 'http://www.reallybigpictures.com' },
	{ name: 'Sonic VR', img: 'SonicVR.png', site: 'http://www.sonicvr.com' },
	{ name: 'Greenlight VR', img: 'GreenlightVR.png', site: 'http://www.greenlightvr.com' },
	{ name: 'Side Effects Software', img: 'Houdini.png', site: 'http://www.sidefx.com/' },
	{ name: 'Meta', img: 'Meta.png', site: 'http://getmeta.com' },
	{ name: 'Shape Space VR', img: 'ShapeSpace.jpg', site: 'http://www,ShapeSpaceVR.com', custom_class: 'half' },
	{ name: 'Selvz', img: 'Selvz.png', site: 'http://www.selvz.com', custom_class: 'half' },
	{ name: 'SubPac', img: 'SubPac.png', site: 'http://www,thesubpac.com' },
	{ name: 'VRecover', img: 'VRecover.png', site: 'http://www.vrecover.com' },
	{ name: 'Kor FX', img: 'KorFX.png', site: 'http://korfx.com/' },
	{ name: 'Emblematic Group', img: 'Emblematic.jpg', site: 'https://emblematicgroup.squarespace.com/' },
	{ name: 'Epson', img: 'Epson.png', site: 'http://www.epson.com' },
	{ name: 'Specular Theory', img: 'SpecularTheory.png', site: 'http://www.speculartheory.com', custom_class: 'half' },
	{ name: 'Trilby', img: 'Trilby.png', site: 'http://www.trilbygames.com', custom_class: 'half' },
	{ name: 'Merxius', img: 'Merxius.png', site: 'http://merxius.in/' },
	{ name: 'Casino VR', img: 'CasinoVR.png', site: 'http://casino-vr.com/' },
	{ name: 'Puni', img: 'Puni.png', site: 'http://edwon.tv/puni/' },
	{ name: 'Appzion', img: 'Appzion.jpg', site: 'http://www.appzion.com/' },
	{ name: 'xRez', img: 'xRez.png', site: 'http://www.xrez.com/' },
	{ name: 'Lucid', img: 'Lucid.png', site: 'http://lucidcam.com/', custom_class: 'half' },
	{ name: 'White Hawk Software', img: 'WhiteHawk.png', site: 'http://www.whitehawksoftware.com/', custom_class: 'half' },
	{ name: 'SVVR', img: 'SVVR.png', site: 'http://svvr.com/' },
	{ name: 'Virtusphere', img: 'Virtusphere.png', site: 'http://www.virtusphere.com/' },
	{ name: 'Young Park Game Lab', img: 'YoungParkGameLab.png', site: 'http://www.youngparkgamelab.com' },
	{ name: 'Altspace VR', img: 'AltspaceVR-new.png', site: 'http://www.altvr.com/' },
	{ name: '3DiVi', img: '3DiVi.png', site: 'http://www.nuitrack.com' },
	{ name: 'VR Sports', img: 'VRSports.png', site: 'http://www.vrsports.us', custom_class: 'half' },
	{ name: 'Mirada', img: 'Mirada.png', site: 'http://mirada.com/', custom_class: 'half' },
	{ name: 'Link VR', img: 'Link.png', site: 'http://www.link-vr.com' },
	{ name: 'Nano VR', img: 'NanoVR.png', site: 'http://www.nanovr.com', custom_class: 'center' }
])

Speaker.create([
	# { name: '', img: '', bio: '' }
	{ name: 'Duncan Trussell', img: 'DuncanTrussel.jpg', bio: 'Host of the Duncan Trussell Family Hour Podcast, Comdeian, VR Evangelist', is_featured: true },
	{ name: 'Dave Taylor', img: 'DaveTaylor.jpg', bio: 'Game Producer, Developer on Doom and Quake', is_featured: true },
	{ name: 'Jonnie Ross', img: 'JonnieRoss.jpg', bio: 'Co-Founder at VRLA', is_featured: true },
	{ name: 'Jim Willson', img: 'JimWillson.jpg', bio: 'Director, Immersive Products & VR at Samsung', is_featured: true },
	{ name: 'Matthew Gratzner', img: 'MatthewGratzner.jpg', bio: 'Director, Designer, VR, VFX & Co-Founder at NewDealStudios', is_featured: true },
	{ name: 'Alex Rosenfeld', img: 'AlexRosenfeld.jpg', bio: 'Founder & CEO at Vrideo', is_featured: true },
	{ name: 'David Cramer', img: 'DavidCramer.jpg', bio: 'SVP of Corporate Strategy at NextVR' },
	{ name: 'Bruce Wooden', img: 'BruceWooden.jpg', bio: 'Head of Developer & Community Relations at AltspaceVR' },
	{ name: 'James Jensen', img: 'JamesJensen.jpg', bio: 'CTO at The Void' },
	{ name: 'Mike Armstrong', img: 'MikeArmstrong.jpg', bio: 'Founder & Developer at Riftmax' },
	{ name: 'Mike Murdock', img: 'MikeMurdock.jpg', bio: 'Co-Founder & Creative Director at Otherworld Interactive' },
	{ name: 'E McNeil', img: 'EMcNeil.jpg', bio: 'Creator of Darknet' },
	{ name: 'Demetrius Wren', img: 'DemetriusWren.jpg', bio: 'Film Maker' },
	{ name: 'Robert Hernandez', img: 'RobertHernandez.jpg', bio: 'Associate Professor of Professional Practice at USC Annenberg' },
	{ name: 'Matthew Terndrup', img: 'MatthewTerndrup.jpg', bio: 'VR Journalist' },
	{ name: 'Ivan Blaustein', img: 'IvanBlaustein.jpg', bio: 'Director, Product Integration at VRCade' },
	{ name: 'Christina Heller', img: 'ChristinaHeller.jpg', bio: 'CEO at VR Playhouse' },
	{ name: 'Nonny de la Peña', img: 'NonnyDeLaPena.jpg', bio: 'CEO & Founder at Emblematic Group' },
	{ name: 'Alexx Henry', img: 'AlexxHenry.jpg', bio: 'CEO at blueVishnu' },
	{ name: 'Will Mason', img: 'WillMason.jpg', bio: 'Editor in Chief at UploadVR' },
	{ name: 'Todd Revolt', img: 'ToddRevolt.jpg', bio: 'Director of Strategic Alliances at Meta' },
	{ name: 'Karl Krantz', img: 'KarlKrantz.png', bio: 'Organizer of SVVR' },
	{ name: 'St. John Colon', img: 'StJohnColon.jpg', bio: 'Lecturer - USC, Computer Science' },
	{ name: 'Theresa Duringer', img: 'TheresaDuringer.jpg', bio: 'Co-Creator of Bazaar' },
	{ name: 'Gabriel Miller', img: 'GabrielMiller.jpg', bio: 'Director of R&D at the San Diego Zoo' },
	{ name: 'Walt Scacchi', img: 'WaltScacchi.jpg', bio: 'Head of R&D for VR at UCI' },
	{ name: 'Jacki Morie', img: 'JackieMorie.jpg', bio: 'Founder, Chief Scientist at All These Worlds' },
	{ name: 'David Knight', img: 'DavidKnight.jpg', bio: 'CEO at Terbine' },
	{ name: 'Liam Kennedy', img: 'LiamKennedy.jpg', bio: 'Inventor of the ISS-Above' },
	{ name: 'Ben Miller', img: 'BenMiller.jpg', bio: 'Director of Content at WEVR' },
	{ name: 'Morris May', img: 'MorrisMay.jpg', bio: 'CEO of Specular Theory' },
	{ name: 'Brent Bushnell', img: 'BrentBushnell.jpg', bio: 'CEO of Two Bit Circus' },
	{ name: 'Telly L', img: 'TellyL.jpg', bio: 'Adult Business Development Consultant' },
	{ name: 'Ela Darling', img: 'ElaDarling.jpg', bio: 'VRTube', custom_class: 'margin-sml' },
	{ name: 'Ricky Booker', img: 'RickyBooker.jpg', bio: 'CEO at CumFundMe', custom_class: 'mobile-center' }
])

Sponsor.create([
	# { name: '', rank: '', img: '', site: '' }
	{ name: 'Next VR', rank: 'Diamond', img: 'NextVR.png', site: 'http://www.nextvr.com/', custom_class: 'lrg' },
	{ name: 'San Diego Zoo', rank: 'Diamond', img: 'TechtoReconnect.png', site: 'http://www.techtoreconnect.org', custom_class: 'lrg' },
	{ name: 'Fast Start Studios', rank: 'Ruby', img: 'FastStart.png', site: 'http://www.faststartstudio.com/', custom_class: 'lrg' },
	{ name: 'Altspace VR', rank: 'Ruby', img: 'AltspaceVR-new.png', site: 'http://altvr.com/', custom_class: 'lrg' },
	{ name: 'Real Office Centers', rank: 'Ruby', img: 'ROC.jpg', site: 'http://www.realofficecenters.com/' },
	{ name: 'UCI', rank: 'Ruby', img: 'UCICove.png', site: 'http://innovation.uci.edu/' },
	{ name: 'Unity', rank: 'Ruby', img: 'Unity.png', site: 'http://unity3d.com/' },
	{ name: 'Welens', rank: 'Emerald', img: 'Welens.png', site: 'http://www.welens.com/' },
	{ name: 'Void', rank: 'Emerald', img: 'Void.png', site: 'https://thevoid.com/', custom_class: 'half' },
	{ name: 'Famous Group', rank: 'Emerald', img: 'FamousGroup.png', site: 'http://www.thefamousgroup.com/', custom_class: 'half' },
	{ name: 'Boost', rank: 'Emerald', img: 'Boost.svg', site: 'https://www.boost.vc/' },
	{ name: 'Side Effects Software', rank: 'Emerald', img: 'Houdini.png', site: 'http://www.sidefx.com/' },
	{ name: 'Hack A Day', rank: 'Emerald', img: 'HackADay-new.png', site: 'http://hackaday.com/' },
	{ name: 'VR Cade', rank: 'Emerald', img: 'VRCade.png', site: 'http://vrcade.com/' },
	{ name: 'VGDA', rank: 'Community', img: 'VGDA.png', site: 'http://www.vgda.net/' },
	{ name: 'OCVR', rank: 'Community', img: 'OCVR.png', site: 'http://orangecountyvr.com/' },
	{ name: 'Digital LA', rank: 'Community', img: 'DigitalLA.jpg', site: 'http://digitalla.net/' },
	{ name: 'VRLA', rank: 'Community', img: 'VRLA.png', site: 'http://www.virtualrealityla.com/', custom_class: 'med' },
	{ name: 'SVVR', rank: 'Community', img: 'SVVR.png', site: 'http://svvr.com/', custom_class: 'med' },
	{ name: 'VRLB', rank: 'Community', img: 'VRLB.png', site: 'http://www.meetup.com/Long-Beach-Virtual-Reality-Meetup/', custom_class: 'med' },
	{ name: 'SDVR', rank: 'Community', img: 'SDVR.png', site: 'http://www.meetup.com/San-Diego-Virtual-Reality/', custom_class: 'med' },
	{ name: 'VR Fest', rank: 'Community', img: 'VRFest.png', site: 'http://3dff.org/', custom_class: 'margin-sml sml' },
	{ name: 'SFVR', rank: 'Community', img: 'SFVR.png', site: 'http://www.meetup.com/virtualreality/', custom_class: 'sml' },
	{ name: 'OC Hackerz', rank: 'Community', img: 'OCHackerz.jpg', site: 'http://www.meetup.com/OCHackerz/', custom_class: 'sml' },
	{ name: 'Survios', rank: 'Community', img: 'Survios.png', site: 'http://survios.com/', custom_class: 'nrml' },
	{ name: 'KHS', rank: 'Community', img: 'KHS.png', site: 'http://www.khslaw.com/', custom_class: 'nrml' },
	{ name: 'Kokiri', rank: 'Community', img: 'Kokiri.png', site: 'http://www.kokirilab.com/', custom_class: 'nrml' },
	{ name: 'Brainitch', rank: 'Community', img: 'Brainitch.png', site: 'http://www.brainitch.com/' },
	{ name: 'Cyber Code Twins', rank: 'Community', img: 'CyberCodeTwins.jpg', site: 'https://www.facebook.com/cybercodetwins' },
	{ name: 'Web 3D', rank: 'Community', img: 'Web3D.jpg', site: 'http://www.web3d.org/' },
	{ name: 'Duncan Trussell', rank: 'Media', img: 'DuncanTrussellFH.png', site: 'http://duncantrussell.com/', custom_class: 'duncan' },
	{ name: 'VR Scout', rank: 'Media', img: 'VRScout.png', site: 'http://vrscout.com/' },
	{ name: 'UploadVR', rank: 'Media', img: 'Upload.png', site: 'http://uploadvr.com/' },
	{ name: 'VRfocus', rank: 'Media', img: 'VRFocus.png', site: 'http://vrfocus.com/' },
	{ name: 'VR Digest', rank: 'Media', img: 'VRDigest.png', site: 'http://vrdigest.com/', custom_class: 'tiny' },
	{ name: 'Voices of VR', rank: 'Media', img: 'VoicesOfVR.jpg', site: 'http://voicesofvr.com/', custom_class: 'tiny' },
	{ name: 'VR Reporter', rank: 'Media', img: 'VRReporter.jpg', site: 'https://virtualrealityreporter.com/', custom_class: 'tiny' },
	{ name: 'Inner Rift', rank: 'Media', img: 'InnerRift.jpg', site: 'http://www.innerrift.com/', custom_class: 'tiny' },
	{ name: 'Qgits', rank: 'Media', img: 'Qgits.png', site: 'http://www.qgits.org/', custom_class: 'tiny' },
	{ name: 'Yourift', rank: 'Media', img: 'YouRift.jpg', site: 'http://yourift.com/', custom_class: 'half margin-sml' },
	{ name: 'Enter VR', rank: 'Media', img: 'EnterVR.png', site: 'http://entervr.net/', custom_class: 'half' },
	{ name: 'VR Circle', rank: 'Media', img: 'VRCircle.png', site: 'http://www.vrcircle.com/', custom_class: 'half' },
	{ name: 'Ultraculture', rank: 'Media', img: 'UltraCulture.jpg', site: 'http://ultraculture.org/', custom_class: 'half mobile-center' },
	{ name: 'Road to VR', rank: 'Media', img: 'RoadToVR.png', site: 'http://roadtovr.com/', custom_class: 'margin-sml' },
	{ name: 'Zap Chain', rank: 'Media', img: 'ZapChain.png', site: 'http://www.zapchain.com/' },
	{ name: 'VR Live', rank: 'Broadcasting', img: 'VRLive.png', site: 'http://www.vrlive.com/', custom_class: 'lrg' },
	{ name: 'Vrideo', rank: 'Broadcasting', img: 'VRideo.png', site: 'http://www.vrideo.com', custom_class: 'lrg' }
])

Worker.create([
	# { name: '', img: '', bio: '' }
	{ name: 'Dylan Watkins', img: 'DylanWatkins.jpg', bio: 'Organizer' },
	{ name: 'Christopher Cain', img: 'ChristopherCain.jpg', bio: 'Volunteer Coordinator' },
	{ name: 'Matthew Terndrup', img: 'MatthewTerndrup.jpg', bio: 'Panels & Teams Coordinator' },
	{ name: 'Azia Celestino', img: 'AziaCelestino.jpg', bio: 'AV - Coordinator' },
	{ name: 'Aaron Lane', img: 'AaronLane.jpg', bio: 'Business Development' },
	{ name: 'Matt Kinney', img: 'MattKinney.jpg', bio: 'Developer Relations' },
	{ name: 'Brian Levine', img: 'BrianLevine.jpg', bio: 'Conference App Developer', custom_class: 'margin-sml' },
	{ name: 'Sam Walston', img: 'SamWalston.jpg', bio: 'Web Developer' }
])


